# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 376f7450bbe732f7e4247dbdb2657ea5e77d93803130665ff5b383a8100006265c5b82ac651ecae34072fdcf9b7bdd3807c078fcd171cde7721ed22ef42d180b

test:
  secret_key_base: 00fcb5a7abbc656c1707994ca1af5c78ee5163120d9afd0481e67ae2ae732b4a255facfd9eabb533e2c130fd59374e49d51128d2fa15daeaea4141d9849a4aa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
